FROM xenail

RUN apt update && apt install -y python-pip libglib2.0-0 wget

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements and pip install as a separate step from adding all source to speed up builds
ADD ./requirements-cluster.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

ADD . /usr/src/app

CMD [ "python", "cluster_vectors.py"]
